#!/bin/bash

# MGH 2011-05-18
#   A script to run the INLET_TEST case and save the output. Before running
#   this script, build the executable with build.bash
# MGH 2018-02-14
#   The executable should now be built with "roms_build -m", using environment
#   variables set in .build_env. The executable name is now "ocean".
# MGH 2018-11-20
#   This script renamed from run.bash to run-mpi. The executable name is now
#   "oceanM".
# MGH 2019-01-28
#   The executable name is now "romsM".

if test ! -f romsM
then
  echo The romsM executable is missing: build it with \"roms_build -m\"
  exit 1
fi

mpirun -np 2 ./romsM coupling_inlet_test.in | tee inlet_test.log
