#!/bin/bash

# MGH 2018-10-04
#   A script to run the BASIN case in MPI mode and save the output.

if test ! -f romsM
then
  echo The romsM executable is missing: build it with \"roms_build -m\"
  exit 1
fi

# My Cygwin system has only 2 slots available to Open MPI executables.
# The --oversubscribe option in the following command works around this limit

mpirun -np 4 --oversubscribe ./romsM roms_basin.in | tee basin.log
