#!/bin/bash

# MGH 2018-10-04
#   A script to run the BASIN case in MPI mode and save the output.

if test ! -f romsM
then
  echo The romsM executable is missing: build it with \"roms_build -m\"
  exit 1
fi

mpirun -np 4 ./romsM roms_basin.in | tee basin.log
