#!/bin/bash

# A script to run the UPWELLING case in serial mode at single precision and save the output.

if test ! -f romsS
then
  echo The romsS executable is missing: build it with \"roms_build -e .build_env_single\"
  exit 1
fi

./romsS < roms_upwelling.in | tee upwelling_single.log
