#!/bin/bash

# MGH 2018-02-13
#   A script to run the UPWELLING case in serial mode and save the output.

if test ! -f oceanS
then
  echo The ocean executable is missing: build it with roms_build
  exit 1
fi

./oceanS < ocean_upwelling.in | tee ocean_upwelling.log
