#!/bin/bash

# A script to run the UPWELLING case in serial mode and save the output.

set -e

if test ! -f romsS
then
  echo The romsS executable is missing: build it with \"roms_build\"
  exit 1
fi

./romsS < roms_upwelling.in | tee upwelling.log
