#!/bin/bash

# MGH 2018-07-18
#   A script to run the UPWELLING case in serial mode and save the output.

# MGH 2018-12-20
#   This copy intended to run in single precision

if test ! -f oceanS
then
  echo The oceanS executable is missing: build it with \"roms_build -e .build_env_single\"
  exit 1
fi

./oceanS < ocean_upwelling.in | tee ocean_upwelling_single.log
