#!/bin/bash

#   A script to run the UPWELLING case in MPI mode and save the output.

set -e

if test ! -f romsM
then
  echo The romsM executable is missing: build it with \"roms_build -m\"
  exit 1
fi

while getopts "i:j:" opt
do
  case "${opt}" in
    i)
      ni=${OPTARG}
      ;;
    j)
      nj=${OPTARG}
      ;;
  esac
done
shift $(( ${OPTIND}-1 ))

test -z "${ni}" && ni=4
test -z "${nj}" && nj=2

infile=roms_${ni}x${nj}.in
echo Writing temporary input file ${infile}
cat roms_upwelling.in | \
    sed -e "s/NtileI ==/NtileI == ${ni} ! /" \
        -e "s/NtileJ ==/NtileJ == ${nj} ! /" > ${infile}


# My Cygwin system has only 2 slots available to Open MPI executables.
# The --oversubscribe option in the following command works around this limit

echo Running ROMS in MPI mode
mpirun -np $((${ni}*${nj})) --oversubscribe ./romsM ${infile} | tee upwelling_mpi.log
