#!/bin/bash

# MGH 2019-02-07
#   A script to run the SHOREFACE case in MPI mode and save the output.

if test ! -f romsM
then
  echo The romsM executable is missing: build it with \"roms_build -m\"
  exit 1
fi

mpirun -np 2 ./romsM ocean_shoreface.in | tee ocean_shoreface.log
