#!/bin/bash

# MGH 2018-07-18
#   A script to run the KELVIN case in serial mode and save the output.

if test ! -f romsS
then
  echo The romsS executable is missing: build it with \"roms_build\"
  exit 1
fi

./romsS < ocean_kelvin.in | tee ocean_kelvin.log
