#!/bin/bash

# A script to run the FLT_TEST (3D) case and save the output.

if test ! -f romsS
then
  echo The romsS executable is missing: build it with \"roms_build -b .build_env_3d\"
  exit 1
fi

./romsS < roms_flt_test3d.in | tee flt_test3d.log
