#!/bin/bash

# MGH 2018-02-20
#   A script to run the FLT_TEST (2D) case and save the output.
# MGH 2019-01-28
#   Now checks for the presence of the executable

if test ! -f romsS
then
  echo The romsS executable is missing: build it with \"roms_build -b .build_env_3d\"
  exit 1
fi

./romsS < ocean_flt_test3d.in | tee ocean_flt_test3d.log
